### ISSUE TITLE
TMobilePermissionsAndroid.SetAndroidVersion error on androd 5.1

### ISSUE THREAD

**Issue by pieomy** [adrianosantostreina/MobilePermissions#1]
Hi,

Thank you for share this component, very useful.

I have error on android 5.1 after MobilePermissions1.Apply;
" '5.1' is not a valid integer value. "

it's probably on procedure TMobilePermissionsAndroid.SetAndroidVersion;
FAndroidVersion := StrToInt(VVersionOSStr);

there is a alternative and easy way to find android version 
System.SysUtils.TOSVersion.Major; (return Integer like 4,5,6,7,8,9,10)

more info: https://forums.embarcadero.com/thread.jspa?threadID=183785

**Comment by adrianosantostreina** [comment]
Hi,

Thanks.
We will fix this bug, thanks very much.

;)

**Comment by adrianosantostreina** [comment]
Bug fixed.

**Comment by pieomy** [comment]
Thank you
