### ISSUE TITLE
Component is not asking for the necessary rights

### ISSUE THREAD

**Issue by MichaelLurie** [adrianosantostreina/MobilePermissions#11]
Hi
Wonderful idea - hope I can make it work: I placed the component on a form and selected the rights I need, but when the software runs on Android is does not ask for the permissions. Do I have to do somethimg like a check before ? 

Additionally I need the microphon permission which I can't find in the list.

Advice appreciated
Michael

**Comment by DeveloppeurPascal** [comment]
Hi,

To activate the permissions you need to call "Apply" method of the TMobilePermissions component.

For the microphon permission, can you give the exact permission string from Android doc ?

**Comment by adrianosantostreina** [comment]
Yes, sure.
