### ISSUE TITLE
Android 11 Error

### ISSUE THREAD

**Issue by AnonBit** [adrianosantostreina/MobilePermissions#16]
Did DEMO One with RAD Studio 11 Alexandria.

![Screenshot_20211004-141942_Project1](https://user-images.githubusercontent.com/6508486/135850756-5fcf8788-87d0-4e42-ad8b-cc82fc841710.png)

**Comment by adrianosantostreina** [comment]
Finally we managed to tweak everything needed in the component to be compatible with Delphi 11.x

We are preparing a new version with other new properties.

Do your tests and let us know.
Thanks
