### ISSUE TITLE
ACCESS BACKGROUND LOCATION not found to apply it on Android11

### ISSUE THREAD

**Issue by armadix** [adrianosantostreina/MobilePermissions#17]
Hi your component is awesome by the way.
I cannot find for android11 to ACCESS_BACKGROUND_LOCATION using this component could I request to add this feature on your next build version 0.6 much appreciated if this will be implemented thanks.

**Comment by acarlomagno** [comment]
it is important for android 11

https://developer.android.com/reference/android/Manifest.permission#ACCESS_BACKGROUND_LOCATION

**Comment by adrianosantostreina** [comment]
Yes, sure.
Exists any others properties, but I'm still working in updates.

**Comment by adrianosantostreina** [comment]
Hello,

Some permission implementations have been mapped into Delphi, but Embarcadero has not encapsulated them in such a way that access outside the permissions window is not possible. Therefore, this property will not be implemented in the component, the programmer must mark it manually within the Project > Options > Application > User Permissions window.

Sorry about that.
