### ISSUE TITLE
Erro CALL_COMPANION_APP Delphi 11

### ISSUE THREAD

**Issue by aslsoftware** [adrianosantostreina/MobilePermissions#29]
![image](https://user-images.githubusercontent.com/16899680/204092149-2fad5f61-82bd-4dbc-8425-b4e22d208717.png)

Estou com este erro ao compilar no delphi 11, sabe dizer o que está errado? 

Obrigado

**Comment by hcoineto** [comment]
I´m with the same issue.  Delphi 11.2.  Mobile Permissions Source code 2 downloaded today (16/12/2022);

**Comment by cleberDeveloper** [comment]
Comentei o código e compilei. Não sei se existe algo relacionado, mas as permissões pararam de ser requisitadas e com isso o app não abre.

**Comment by dpcroghan** [comment]
Hello, I am having the same issue.  I am using Delphi 11.2 update 2

**Comment by adrianosantostreina** [comment]
Finally we managed to tweak everything needed in the component to be compatible with Delphi 11.x

We are preparing a new version with other new properties.

Do your tests and let us know.
Thanks
