### ISSUE TITLE
Erro ao instalar no Delphi 11.1 O sistema não pode encontrar o arquivo especificado MobilePermissions.bpl

### ISSUE THREAD

**Issue by henriquebaumgarten** [adrianosantostreina/MobilePermissions#32]
Can't load package MobilePermissions.bpl.
O sistema não pode encontrar o arquivo especificado

![erro instalação](https://user-images.githubusercontent.com/15846456/207439344-439fc6bc-13ce-41b4-a165-64b7ac5552fe.png)

Alguém passou por isso ?

**Comment by adrianosantostreina** [comment]
Instale usando o Get It Package Manager por dentro do Delphi em Tools.

**Comment by adrianosantostreina** [comment]
In this case, just open Delphi in Administrator Mode, however we have already adjusted it so that it is no longer necessary to open it in Administrator Mode.
