### ISSUE TITLE
Mobile Components does not work at all.  MobilePermissions.Component

### ISSUE THREAD

**Issue by davewr** [adrianosantostreina/MobilePermissions#38]
MobilePermissions.Component
Highlights as an error.

I installed it as an administrator and normally  ---   same behavior.

MobilePermissions.Component not found --  and of course, nothing works after that.

This is using your demo.  (One Drive is  disabled for compiles)

C:\Users\davew\OneDrive\Documents\Embarcadero\Studio\22.0\CatalogRepository\MobilePermissions-2.1\Demos\Tests\UntMain.pas(8,98): error F2613: F2613 Unit 'MobilePermissions.Component' not found.

unit UntMain;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  FMX.Types, FMX.Controls, FMX.Forms, FMX.Graphics, FMX.Dialogs, MobilePermissions.Model.Signature,
  MobilePermissions.Model.Dangerous, MobilePermissions.Model.Standard, MobilePermissions.Component,
  FMX.Controls.Presentation, FMX.StdCtrls, System.Math.Vectors, FMX.Controls3D,
  FMX.Layers3D, FMX.ListBox, FMX.Layouts;

**Comment by davewr** [comment]
Just a note that it is  Delphi 11.3. 
Version .5   is working on my  Delphi 11patch 1.

**Comment by adrianosantostreina** [comment]
1. It is no longer necessary to open Delphi in Administrator Mode.
2. You need to indicate to Delphi where the component's sources are, normal operation in any component.

To do this, open Tools > Options > Language > Delphi > Library > Library Path

Add the path to the component in the Library Path.

Do this for Win32, Win64, Android32, Android64.

**Comment by davewr** [comment]
...{USER_LOCATION}\Documents\Embarcadero\Studio\22.0\CatalogRepository\MobilePermissions\Source\Component

The above works.

Just adding a link to the source does not.

**Comment by davewr** [comment]
Or better add:
$(BDSCatalogRepository)\MobilePermissions-2.1\Source\Component
That seems to work and eats less space
As an additional point people are always complaining about the effects of OneDrive -- it introduces download delays and can cause component failure due to file copy delays.
A directory can be marked through properties that the files will ALWAYS be kept on the device.
