### ISSUE TITLE
Error MobilePermissions.Component.hpp

### ISSUE THREAD

**Issue by sdzccs** [adrianosantostreina/MobilePermissions#5]
D:\XE_Kj\MobilePermissions\Package\Android\Release\MobilePermissions.Component.hpp(39,55): error E2017: expected a class or namespace
  D:\XE_Kj\MobilePermissions\Package\Android\Release\MobilePermissions.Component.hpp(39,55): error E1558: reference to 'Fmx' is ambiguous
  c:\xe7\include\android\fmx\FMX.TreeView.hpp(36,10): error E3056: candidate found by name lookup is 'Fmx'
  D:\XE_Kj\MobilePermissions\Package\Android\Release\MobilePermissions.UsesPermissions.FMX.Signature.hpp(26,10): error E3056: candidate found by name lookup is 'Mobilepermissions::Usespermissions::Fmx'
  D:\XE_Kj\MobilePermissions\Package\Android\Release\MobilePermissions.Component.hpp(39,67): error E969: expected class name
  D:\XE_Kj\MobilePermissions\Package\Android\Release\MobilePermissions.Component.hpp(41,9): error E2017: expected a class or namespace
  D:\XE_Kj\MobilePermissions\Package\Android\Release\MobilePermissions.Component.hpp(41,9): error E1558: reference to 'Fmx' is ambiguous
  c:\xe7\include\android\fmx\FMX.TreeView.hpp(36,10): error E3056: candidate found by name lookup is 'Fmx'
  D:\XE_Kj\MobilePermissions\Package\Android\Release\MobilePermissions.UsesPermissions.FMX.Signature.hpp(26,10): error E3056: candidate found by name lookup is 'Mobilepermissions::Usespermissions::Fmx'

**Comment by adrianosantostreina** [comment]
Use Delphi Rio 10.x or higher.

**Comment by sdzccs** [comment]
Use Delphi Rio 10.3.3 . Use C++Builder 10.3.3

**Comment by sdzccs** [comment]
unable to find staatic library:libvclx.a
unable to find staatic library:libvclimg.a

**Comment by sdzccs** [comment]
unable to find staatic library:libvclactnband.a

**Comment by adrianosantostreina** [comment]
This component was develop in Delphi 10.3.3 and not is compatible with C++.
Follow the instructions to install this component.
