### ISSUE TITLE
error permission on android 10

### ISSUE THREAD

**Issue by Marijsoft** [adrianosantostreina/MobilePermissions#6]
Hello i have a little problem when i try to apply the permission on android 10 i have the message '' is not a valid integer value with your demo on delphi 10.4

**Comment by adrianosantostreina** [comment]
Hello,
This bug has been fixed for a few months now. Make sure that the component version is correct. Completely uninstall the component and redo the installation.

**Comment by Marijsoft** [comment]
i download again from repository your component uninstall and 
deleted all old files in the folder and extracted the new file for remository. Run delphi 10.4 with administrator clean build compile install it's ok but when i try to test your demo in my phone (android 10) have the same message  
![1](https://user-images.githubusercontent.com/4884515/85320136-e6611a80-b4c2-11ea-9710-b3558bb53349.jpeg)
![2](https://user-images.githubusercontent.com/4884515/85320154-eb25ce80-b4c2-11ea-9556-7f5a0345accd.jpeg)

**Comment by adrianosantostreina** [comment]
Forget DEMO.
Create a new projetct Multi-Devive Application Delphi
Drop a new instance of MobilePermission onto form
Type a method on event OnCreate like below sample:
MobilePermission1.Dangerous.Camera := True;
MobilePermission1.Apply;
Run in your device

**Comment by adrianosantostreina** [comment]
Closed
