### ISSUE TITLE
erro ao compilar...

### ISSUE THREAD

**Issue by aloisiog** [adrianosantostreina/MobilePermissions#7]
ao compilar a aplicação para android nas versões XE8 e XE10.2 apresenta erro em 
mobilepermissions.JNI.Os - JJManifest_permissionClass;

[DCC Error] MobilePermissions.UsesPermissions.FMX.Base.pas(97): E2003 Undeclared identifier: 'TJManifest_permission'

o que pode ser falta  instalar algo?

**Comment by adrianosantostreina** [comment]
O componente é para Delphi 10.3.3 em diante. Abaixo dele, não é necessário.
